VIA_ENABLE = yes
ENCODER_MAP_ENABLE = yes

QUANTUM_PAINTER_ENABLE = yes
QUANTUM_PAINTER_DRIVERS += gc9a01_spi
QUANTUM_PAINTER_LVGL_INTEGRATION = yes

OPT_DEFS = -O2
SRC += thintel15.qff.c

AUDIO_ENABLE = yes
AUDIO_DRIVER = pwm_hardware
