RGBLIGHT_ENABLE     = no
RGB_MATRIX_ENABLE   = yes
MOUSEKEY_ENABLE 	= yes
NKRO_ENABLE 		= yes
OLED_ENABLE 		= yes
OLED_DRIVER 	   	= SSD1306
ENCODER_ENABLE 		= no
EXTRAKEY_ENABLE 	= yes
AUTO_SHIFT_ENABLE 	= yes

LTO_ENABLE 			= yes
CONSOLE_ENABLE 		= no
COMMAND_ENABLE 		= no
SPACE_CADET_ENABLE 	= no
GRAVE_ESC_ENABLE 	= no 
MAGIC_ENABLE 		= no
MUSIC_ENABLE 		= no