// ハードウェアライブラリのアサーションを無効にする
/* #ifdef PARAM_ASSERTIONS_ENABLED
#undef PARAM_ASSERTIONS_ENABLED
#endif
#define PARAM_ASSERTIONS_ENABLED(x) 0 */

#ifndef CONFIG_H
#define CONFIG_H

// #include "config_common.h"

// disable_assertions.c
#undef PARAM_ASSERTIONS_ENABLED_LOCK_CORE
#undef PARAM_ASSERTIONS_ENABLED_TIME
#undef PARAM_ASSERTIONS_ENABLED_PHEAP
#undef PARAM_ASSERTIONS_ENABLED_NETWORK
#undef PARAM_ASSERTIONS_ENABLED_MEMORY
#undef PARAM_ASSERTIONS_ENABLED_FILE
#undef PARAM_ASSERTIONS_ENABLED_GRAPHICS
#undef PARAM_ASSERTIONS_ENABLED_SOUND
#define PARAM_ASSERTIONS_ENABLE_ALL 0
#define PARAM_ASSERTIONS_DISABLE_ALL 1

#define MATRIX_ROWS 3
#define MATRIX_COLS 3

#define DIRECT_PINS { \
    { GP28, GP6, GP2 }, \
    { GP29, GP7, GP1 }, \
    { GP0 } \
}

#define ENCODERS_PAD_A { GP26, GP4 }
#define ENCODERS_PAD_B { GP27, GP3 }

#define DEBOUNCE 5

#define DYNAMIC_KEYMAP_LAYER_COUNT 1

// ホールエフェクトセンサのピン設定
/* #define HALL_SENSOR_PIN_W GP6
#define HALL_SENSOR_PIN_A GP29
#define HALL_SENSOR_PIN_S GP7
#define HALL_SENSOR_PIN_D GP1
#define HALL_SENSOR_PIN_SPC GP0 */

#define EEPROM_HALL_EFFECT_THRESHOLD_ADDR 0

#endif
