MCU = RP2040
SUPPORTS_USB = yes

BOOTLOADER = tinyuf2

BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SLEEP_LED_ENABLE = no
NKRO_ENABLE = yes
WAIT_FOR_USB = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
MIDI_ENABLE = no
AUDIO_ENABLE = no
FAUXCLICKY_ENABLE = no
HD44780_ENABLE = no

DYNAMIC_KEYMAP_ENABLE = yes
VIA_ENABLE = yes

CFLAGS += -Wno-array-bounds
LINKER_FLAGS += -Wl,-Map=$(BUILD_DIR)/$(TARGET).map
